#/bin/bash

if [[ $1 == "" ]]; then
    echo "No arguments supplied. Please provide the directory name to process as the final developer documentation.";
else
    if [ -d "$1" ]; then
        mkdir $1/xsd;
        mkdir $1/css;
        mkdir $1/images;
        cp ../modules/autogenerated/inbloom-*.xsd $1/xsd/;
        cp ../common/css/techpubs.css $1/css/;
        cat image.files | while read imgfilename;
            do
                cp ../common/images/$imgfilename $1/images/;
        done
        echo "Assemble developer docs: COMPLETE"; 
        date;
    else
        echo "Assemble developer docs: ERROR - Directory specified does not exist.";
    fi
fi

