#!/bin/bash

############################################################################
# <repo_root>/sli/config/scripts/documentation/generate_doc_artifacts.sh
#
# This script produces artifacts that are essential for API and data model
# documentation. The output of these artifacts should be copied to the
# modules/autogenerated/ directory under the datastore_docs repository.
# The script used to generate documentation will use the artifacts from there.
#
# REQUIRED: A current inBloom code development environment with the
#           API and ingestion servers running.
# USAGE:    ./generate_doc_artifacts.sh    (no arguments)
# OUTPUT:   ./autogenerated                (directory)
############################################################################

# Generate an XML file (modified WADL schema) that documents all API resources
# for all currently supported versions of the REST API.
function generateApiWadlFile {
    cd ../../../
    pwd
    mvn -U clean install -Dskiptests
    cd api
    pwd
    mvn jetty:run
    cd ../scaffold
    pwd
    mvn package -P apidoc -Dskiptests
    if [[ ! -f "target/doc/eapplication.wadl" ]]; then
        echo "ERROR... API WADL file did not generate successfully. Exiting build process..."
        exit 1
    fi
    cd ../config/scripts/documentation/autogenerated
    cp ../../../../target/doc/eapplication.wadl .
    sed -e 's#\ xmlns="http:\/\/wadl.dev.java.net\/2009\/02"##' eapplication.wadl > eapplication-new.wadl
    mv eapplication-new.wadl eapplication.wadl
    cd ..
}

# Generate XML files (DocBook schema) with sample GET requests for each 
# resource, one file for each currently supported verion of the REST API.
function generateApiGetExamples {
    cd autogenerated/
    ruby get_resources.rb api/src/main/resources/wadl/resources.json cacd9227-5b14-4685-babe-31230476cf3b http://local.slidev.org:8080/api/rest http://localhost/api/rest
    cd ..
}

# Generate the XML file (proprietary) that documents all the entities,
# attributes, and data types in the data model.
function generateDataModelSchema {
    cd autogenerated/
    java -jar modeling/docgen/target/docgen-1.0-SNAPSHOT-jar-with-dependencies.jar -outFolder . -outFile schema.xml -xmiFile <SLI_HOME>/sli/domain/src/main/resources/sliModel/SLI.xmi -domainFile <SLI_HOME>/sli/domain/src/main/resources/sliModel/domains.xml
    cd ..
}

# Copy the XSD that describes the REST API from where it was generated by
# running the docgen JAR.
function grabApiXsd {
    cp ../../../domain/src/main/resources/sliModel/SLI.xsd autogenerated/inbloom-api.xsd
}


# ######################################################################
# MAIN SCRIPT
# ######################################################################
if [ -d "autogenerated" ]; then
    rm -rf autogenerated
fi
mkdir autogenerated
generateApiWadlFile
generateApiGetExamples
generateDataModelSchema
grabApiXsd
echo "Document artifacts complete. See the output directory called 'autogenerated' for results."
